In [19]:
import numpy as np
import random
array1 = np.random.randint(1, 100, 36)
array1

array([50, 11, 59, 79, 99, 34, 84, 81, 81, 78, 94, 90, 97, 63,  9, 19, 45,
       21, 21, 21, 82, 15, 27, 45, 47, 35, 46, 37, 69, 38, 27, 12, 57, 16,
       48, 20])

In [4]:
array2 = np.linspace(10, 100, 36, dtype = int)
array2

array([ 10,  12,  15,  17,  20,  22,  25,  28,  30,  33,  35,  38,  40,
        43,  46,  48,  51,  53,  56,  58,  61,  64,  66,  69,  71,  74,
        76,  79,  82,  84,  87,  89,  92,  94,  97, 100])

In [15]:
array3 = np.arange(6, 220, 6)
array3

array([  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,  78,
        84,  90,  96, 102, 108, 114, 120, 126, 132, 138, 144, 150, 156,
       162, 168, 174, 180, 186, 192, 198, 204, 210, 216])

In [16]:
array3.size


36

In [20]:
array1 + array3

array([ 56,  23,  77, 103, 129,  70, 126, 129, 135, 138, 160, 162, 175,
       147,  99, 115, 147, 129, 135, 141, 208, 147, 165, 189, 197, 191,
       208, 205, 243, 218, 213, 204, 255, 220, 258, 236])

In [21]:
array3 - array1

array([-44,   1, -41, -55, -69,   2, -42, -33, -27, -18, -28, -18, -19,
        21,  81,  77,  57,  87,  93,  99,  44, 117, 111,  99, 103, 121,
       116, 131, 105, 142, 159, 180, 141, 188, 162, 196])

In [22]:
array1 * array2

array([ 500,  132,  885, 1343, 1980,  748, 2100, 2268, 2430, 2574, 3290,
       3420, 3880, 2709,  414,  912, 2295, 1113, 1176, 1218, 5002,  960,
       1782, 3105, 3337, 2590, 3496, 2923, 5658, 3192, 2349, 1068, 5244,
       1504, 4656, 2000])

In [23]:
array3 / array2

array([0.6       , 1.        , 1.2       , 1.41176471, 1.5       ,
       1.63636364, 1.68      , 1.71428571, 1.8       , 1.81818182,
       1.88571429, 1.89473684, 1.95      , 1.95348837, 1.95652174,
       2.        , 2.        , 2.03773585, 2.03571429, 2.06896552,
       2.06557377, 2.0625    , 2.09090909, 2.08695652, 2.11267606,
       2.10810811, 2.13157895, 2.12658228, 2.12195122, 2.14285714,
       2.13793103, 2.15730337, 2.15217391, 2.17021277, 2.16494845,
       2.16      ])

In [24]:
array1.shape

(36,)

In [36]:
array1.reshape(6, 6)

array([[50, 11, 59, 79, 99, 34],
       [84, 81, 81, 78, 94, 90],
       [97, 63,  9, 19, 45, 21],
       [21, 21, 82, 15, 27, 45],
       [47, 35, 46, 37, 69, 38],
       [27, 12, 57, 16, 48, 20]])

In [27]:
array2.reshape(3, 12)

array([[ 10,  12,  15,  17,  20,  22,  25,  28,  30,  33,  35,  38],
       [ 40,  43,  46,  48,  51,  53,  56,  58,  61,  64,  66,  69],
       [ 71,  74,  76,  79,  82,  84,  87,  89,  92,  94,  97, 100]])

In [28]:
array3.reshape(2, 18)

array([[  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,  78,
         84,  90,  96, 102, 108],
       [114, 120, 126, 132, 138, 144, 150, 156, 162, 168, 174, 180, 186,
        192, 198, 204, 210, 216]])

In [37]:
array1.max(axis=0)

array([97, 81, 82, 79, 99, 90])

In [35]:
array1.max(axis=1)

array([99, 94, 97, 82, 69, 57])

In [39]:
array1.max()

99

In [41]:
array2.max()

100

In [42]:
array3.max()

216

In [43]:
array1.min()

9

In [44]:
array2.min()

10

In [53]:
array2 = array2.reshape(6,6)
array2

array([[ 10,  12,  15,  17,  20,  22],
       [ 25,  28,  30,  33,  35,  38],
       [ 40,  43,  46,  48,  51,  53],
       [ 56,  58,  61,  64,  66,  69],
       [ 71,  74,  76,  79,  82,  84],
       [ 87,  89,  92,  94,  97, 100]])

In [55]:
array4 = array1 + array2
array4

array([[ 60,  23,  74,  96, 119,  56],
       [109, 109, 111, 111, 129, 128],
       [137, 106,  55,  67,  96,  74],
       [ 77,  79, 143,  79,  93, 114],
       [118, 109, 122, 116, 151, 122],
       [114, 101, 149, 110, 145, 120]])

In [56]:
array4.max()

151

In [59]:
array4.reshape(9, -1)

array([[ 60,  23,  74,  96],
       [119,  56, 109, 109],
       [111, 111, 129, 128],
       [137, 106,  55,  67],
       [ 96,  74,  77,  79],
       [143,  79,  93, 114],
       [118, 109, 122, 116],
       [151, 122, 114, 101],
       [149, 110, 145, 120]])